//
// Created by zj on 11/30/2023.
//

#ifndef BOOKSTORE_SRC_LOG_H_
#define BOOKSTORE_SRC_LOG_H_

enum class kExceptionType {
  K_SUCCESS,
  K_INVALID_COMMAND,
  K_INVALID_PARAMETER,
  K_NO_SUCH_USER,
  K_INVALID_PASSWORD,
  K_PERMISSION_DENIED,
  K_NO_LOGIN_USER,
  K_USER_ALREADY_EXIST,
  K_USER_IS_LOGGED_IN,
  K_NO_SUCH_BOOK,
  K_NO_SELECTED_BOOK,
  K_DUPLICATED_ISBN,
  K_DUPLICATED_KEYWORDS,
  K_NOT_ENOUGH_LOGS
};

class FinanceLog {};

class UserLog {};

#endif //BOOKSTORE_SRC_LOG_H_
